{ inputs, ... }:
{
  imports = [
    ./ai-code-editors.nix
    ./boot.nix
    ./browsers-extra.nix
    ./communication.nix
    ./gaming-support.nix
    ./flatpak.nix
    ./flutter-dev.nix
    ./fonts.nix
    ./greetd.nix
    ./ly.nix
    ./sddm.nix
    ./hardware.nix
    ./network.nix
    ./nfs.nix
    ./nh.nix
    ./nix-index.nix
    ./packages.nix
    ./printing.nix
    ./productivity.nix
    ./security.nix
    ./services.nix
    ./steam.nix
    ./stylix.nix
    ./syncthing.nix
    ./system.nix
    ./thunar.nix
    ./user.nix
    ./virtualisation.nix
    ./xserver.nix
    inputs.stylix.nixosModules.stylix
  ];
}
